kind: pipeline
type: docker
name: tests

steps:
  - name: 'Устанавливаем композер'
    image: php:8.0-alpine
    commands:
      - composer install

  - name: 'Запускаем тесты'
    image: php:8.0-alpine
    commands:
      - ./vendor/bin/pest

trigger:
  event:
    exclude:
    - promote

---

kind: pipeline
type: docker
name: default

steps:
  - name: 'Удаляем старые файлы'
    image: alpine
    volumes:
      - name: deploy
        path: /home/deploy
    commands:
      - rm -r /home/deploy/*

  - name: 'Копируем файлы в папку релиза'
    image: alpine
    volumes:
      - name: deploy
        path: /home/deploy
    commands:
      - cp -r $PWD/* /home/deploy

volumes:
  - name: deploy
    host:
      path: /home/wtolk/www/www/adfm_installer
  - name: docker_socket
    host:
      path: /var/run/docker.sock




---
kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: 'Устанавливаем права'
    commands:
      - chmod -R 777 /home/wtolk/www/www/adfm_installer
  - name: 'Запускаем композер'
    commands:
      - docker exec -i --user=1000:1000 www_php80_1 sh -c 'cd /home/wtolk/www/www/adfm_installer && composer install'
  - name: 'Собираем утилиту'
    commands:
      - docker exec -i --user=1000:1000 www_php80_1 sh -c 'cd /home/wtolk/www/www/adfm_installer && php adfm app:build adfmInstaller'

depends_on:
  - default





